name: Get token and build UI

on:
  workflow_dispatch:
  # schedule:
  #   - cron: '0 0 1 * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1.2.0

      - name: Get token
        run: |
          echo "VITE_TOKEN=$(curl -X POST -H 'Content-Type: application/json' -d '{\"email\":\"${{ secrets.KB_EMAIL }}\",\"password\":\"${{ secrets.KB_PW }}\",\"ext\":false}' https://api.kickbase.com/user/login | jq -r '.token')" >> $GITHUB_ENV

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Build frontend
        run: bun run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
