name: Get token and build UI

on:
  workflow_dispatch:
  # schedule:
  #   - cron: '0 0 1 * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1.2.0

      - name: Get token
        run: |
          const response = await fetch('https://api.kickbase.com/user/login', {
            method: 'POST',
            headers: {
              'Content-Type': 'application/json',
            },
            body: JSON.stringify({
              email: ${{ secrets.KB_EMAIL }},
              password: ${{ secrets.KB_PW }},
              ext: false,
            }),
          })
          const body = await response.json()
          echo "VITE_TOKEN=${body.token}" >> $GITHUB_ENV

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Build frontend
        run: bun run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: frontend/dist
          github_token: ${{ secrets.TOKEN }}
